include(CheckCXXCompilerFlag)

if(MSVC)
    CHECK_CXX_COMPILER_FLAG("/arch:AVX" COMPILER_OPT_ARCH_AVX_SUPPORTED)
    if(COMPILER_OPT_ARCH_AVX_SUPPORTED)
        message(STATUS "AVX flags enabled for MSVC compiler!")
    else()
        message(STATUS "Unable to add AVX flags for MSVC compiler!")
    endif()
else()
    CHECK_CXX_COMPILER_FLAG("-mavx -mfma" COMPILER_OPT_ARCH_AVX_SUPPORTED)
    if (COMPILER_OPT_ARCH_AVX_SUPPORTED)
        message(STATUS "AVX flags enabled for ${CMAKE_CXX_COMPILER_ID} compiler!")
    else()
        message(STATUS "Unable to enable AVX flags for ${CMAKE_CXX_COMPILER_ID} compiler!")
    endif()
endif()

function(chowdsp_add_avx_flags_if_available target)
    if(MSVC)
        if(COMPILER_OPT_ARCH_AVX_SUPPORTED)
            target_compile_options(${target} PUBLIC /arch:AVX2)
        endif()
    else()
        if (COMPILER_OPT_ARCH_AVX_SUPPORTED)
            target_compile_options(${target} PUBLIC -mavx -mfma)
        endif()
    endif()
endfunction()
